// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ctvjmoorxgczlunzzlgs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN0dmptb29yeGdjemx1bnp6bGdzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzExNzQwOTQsImV4cCI6MjA4Njc1MDA5NH0.P1f16-qBPiih1rsJO9r-Q6ciS5Qy09qGShh0EQ6lwug";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});